replicaCount: 1

image:
  repository: n1vgabay/clalit
  pullPolicy: IfNotPresent
  tag: "0.0.4"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

# podSecurityContext:
#   fsGroup: 2000
#   allowPrivilegeEscalation: false

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
  runAsNonRoot: true

# securityContext:
#   capabilities:
#     drop:
#       - ALL
#   runAsNonRoot: true
#   runAsUser: 1000
#   seccompProfile:
#     type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /liveness
    port: 5000

readinessProbe:
  httpGet:
    path: /readiness
    port: 5000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}