replicaCount: 1

image:
  repository: n1vgabay/clalit
  pullPolicy: Always
  tag: "0.0.10"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /liveness
    port: 5000

readinessProbe:
  httpGet:
    path: /readiness
    port: 5000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumes:
  - name: deployment-volume
    configMap:
      name: deployment-configmap

volumeMounts:
  - name: deployment-volume
    mountPath: /app/templates

envs:
  DB_USER: postgres
  DB_HOST: postgresql-hl
  DB_PORT: 5432
  DB_NAME: postgres

nodeSelector: {}

tolerations: []

affinity: {}